const openerPayoffGroups = [
	{
		opener: 'Are you a Wi-Fi signal',
		payoffs: [
			'I feel a stronger connection every time you are around',
			'my heart just found full bars',
			'you make every room feel connected',
			'I stop buffering when you walk in',
			'you just upgraded my mood to high speed',
			'I did not know chemistry had a signal boost',
			'even my awkwardness connects smoothly with you',
			'you turn weak moments into strong ones',
			'my attention auto-connects to you instantly',
			'you make this conversation crystal clear',
		],
	},
	{
		opener: 'Are you made of copper and tellurium',
		payoffs: [
			'you are genuinely Cu-Te',
			'science just proved my point for me',
			'you are the cutest element in this room',
			'periodic table jokes were made for this moment',
			'you make nerdy lines look smooth',
			'you are the reason chemistry class should be mandatory',
			'you have excellent atomic-level charm',
			'you are my favorite chemical reaction',
			'you make this lab report read like poetry',
			'you are proof that chemistry can be adorable',
		],
	},
	{
		opener: 'Are you a keyboard',
		payoffs: [
			'you are exactly my type',
			'you just pressed all the right keys',
			'I cannot function without your vibe',
			'you make my heart hit enter',
			'you turn my day from lowercase to uppercase',
			'you are the shortcut to my smile',
			'you make every moment type itself perfectly',
			'you are the key to this whole conversation',
			'you make my thoughts autocorrect into compliments',
			'I would never leave you on read-only mode',
		],
	},
	{
		opener: 'Are you a playlist',
		payoffs: [
			'you keep improving my mood',
			'I would put you on repeat all day',
			'you are nothing but bangers',
			'you make every moment sound better',
			'you are my favorite recommendation',
			'you turn this chat into a perfect mix',
			'you are the track I never skip',
			'you make my day flow in perfect rhythm',
			'you are premium-tier vibes only',
			'you sound like my favorite kind of chaos',
		],
	},
	{
		opener: 'Are you a charger',
		payoffs: [
			'you bring my energy right back to one hundred percent',
			'I feel recharged every time you appear',
			'you power up the whole room',
			'you are exactly what my day needed',
			'you give my confidence a full battery',
			'you keep my vibes from running low',
			'you are the boost my mood was waiting for',
			'you turn low power mode off instantly',
			'you are my favorite source of good energy',
			'you make this conversation feel fully charged',
		],
	},
	{
		opener: 'Are you a camera',
		payoffs: [
			'I smile every time I look at you',
			'you make this moment picture perfect',
			'you bring my best angle out',
			'you make memories happen fast',
			'you have instant-classic energy',
			'you turn ordinary moments into highlights',
			'you make everything look better in frame',
			'you are all my favorite snapshots at once',
			'you belong on the front page of my day',
			'you are impossible to blur out of my mind',
		],
	},
	{
		opener: 'Are you a campfire',
		payoffs: [
			'you make this whole place feel warm',
			'I could happily sit with your vibe all night',
			'you light up every conversation',
			'you are cozy in human form',
			'you spark joy instantly',
			'you bring people together without trying',
			'you are the glow-up this night needed',
			'you make awkward moments melt away',
			'you turn chill into unforgettable',
			'you have perfect fireside energy',
		],
	},
	{
		opener: 'Are you a map',
		payoffs: [
			'I keep getting lost in your smile',
			'you point my day in the right direction',
			'you are exactly where I wanted to end up',
			'you make every detour worth it',
			'you are my favorite destination',
			'you make wandering feel like a plan',
			'you turn wrong turns into good stories',
			'I would follow your vibe anywhere',
			'you are the route to my best mood',
			'you make this moment easy to find again',
		],
	},
	{
		opener: 'Are you a magician',
		payoffs: [
			'everyone else disappears when you show up',
			'you just pulled a smile out of thin air',
			'you made my worries vanish instantly',
			'you turn awkward into amazing',
			'you have first-class trick and charm combo',
			'you just made this room impossible to ignore',
			'you turned a normal moment into a wow moment',
			'you make good vibes appear on command',
			'you are the best plot twist in the act',
			'you have undeniable abracadabra energy',
		],
	},
	{
		opener: 'Are you a lighthouse',
		payoffs: [
			'you make everything feel easier to navigate',
			'you guide this whole vibe in the right direction',
			'you are calm, bright, and impossible to miss',
			'you shine exactly when it matters most',
			'you are my favorite safe harbor',
			'you turn chaos into clarity',
			'you make even stormy days look manageable',
			'you are bright without trying too hard',
			'you are steady in the best possible way',
			'you are proof that guidance can be gorgeous',
		],
	},
	{
		opener: 'Are you a cloud',
		payoffs: [
			'you make this day feel lighter',
			'you bring soft energy in the best way',
			'you make everything around you look better',
			'you turned this moment into a daydream',
			'you are the good kind of floating feeling',
			'you made the whole mood more peaceful',
			'you drift in and instantly improve the weather',
			'you are calm, cool, and beautifully timed',
			'you make overthinking evaporate',
			'you are the silver lining every time',
		],
	},
	{
		opener: 'Are you a sunrise',
		payoffs: [
			'you brighten every room you enter',
			'you make early moments worth it',
			'you are the best part of a new day',
			'you make everything look a little golden',
			'you turn sleepy vibes into hopeful vibes',
			'you make this whole chat feel fresh',
			'you are warm without being overwhelming',
			'you are impossible not to notice',
			'you make ordinary mornings feel legendary',
			'you are the glow-up the sky wishes it had',
		],
	},
	{
		opener: 'Are you a snack aisle',
		payoffs: [
			'I cannot pick just one thing to like about you',
			'you are full of excellent choices',
			'you are my favorite kind of temptation',
			'you make self-control very difficult',
			'you are stacked with top-tier options',
			'you make every decision sweeter',
			'you are impossible to pass by',
			'you are dangerously delightful',
			'you are the best part of this stop',
			'you have flavor and personality for days',
		],
	},
	{
		opener: 'Are you a museum',
		payoffs: [
			'you belong in a collection called stunning',
			'I could admire your vibe for hours',
			'you make me slow down and appreciate the moment',
			'you are a masterpiece with excellent timing',
			'you make everything around you feel curated',
			'you have timeless charm',
			'you turn this conversation into an exhibit worth visiting',
			'you are art with great social skills',
			'you make classic look brand new',
			'you are admission-free joy',
		],
	},
	{
		opener: 'Are you a plot twist',
		payoffs: [
			'I did not see this crush coming',
			'you made this conversation instantly more interesting',
			'you changed the whole story in one line',
			'you are the surprise ending I was hoping for',
			'you turned ordinary into unforgettable',
			'you made my expectations look boring',
			'you are the best unexpected part of my day',
			'you showed up right on cue',
			'you gave this chapter main-character energy',
			'you are my favorite narrative upgrade',
		],
	},
	{
		opener: 'Are you a puzzle',
		payoffs: [
			'I would happily spend all day figuring you out',
			'you keep my attention in the best way',
			'you are challenging and charming at the same time',
			'you make every piece of this moment fit',
			'you are exactly the kind of mystery I enjoy',
			'you make curiosity feel fun',
			'you are the kind of problem I want more of',
			'you make overthinking feel productive',
			'you complete this whole vibe',
			'you are worth every second of focus',
		],
	},
	{
		opener: 'Are you a notebook',
		payoffs: [
			'I want to write you into my plans',
			'you are full of ideas I like already',
			'you make me want to take better notes',
			'you turn random thoughts into good ones',
			'you are exactly where good stories begin',
			'you make every page feel more interesting',
			'you are the draft I would never delete',
			'you make me want to keep this chapter going',
			'you are perfectly organized chaos',
			'you are worth underlining twice',
		],
	},
	{
		opener: 'Are you a meteor shower',
		payoffs: [
			'you made wow happen all at once',
			'you light up the sky and my mood together',
			'you make rare moments feel possible',
			'you are the best reason to look up',
			'you turned this night cinematic',
			'you are brilliant and impossible to ignore',
			'you make ordinary nights feel legendary',
			'you are streaking straight into my favorite memory list',
			'you have once-in-a-lifetime energy',
			'you make everything sparkle a little more',
		],
	},
	{
		opener: 'Are you a game save',
		payoffs: [
			'I do not want to lose this moment',
			'you are exactly where I want to pick up next time',
			'you make progress feel exciting',
			'you are my favorite checkpoint today',
			'you make me want to keep playing this conversation',
			'you are worth replaying in my head',
			'you turn good moments into permanent ones',
			'you are the best autosave I could ask for',
			'you make this storyline worth continuing',
			'you are the high score of my day',
		],
	},
	{
		opener: 'Are you a library card',
		payoffs: [
			'I am checking you out respectfully',
			'you have all the right chapters',
			'you make me want to spend more time here',
			'you are overdue for a compliment',
			'you are a classic in the making',
			'you have the kind of story I would reread',
			'you make silence feel interesting',
			'you are fully booked with good vibes',
			'you are my favorite recommendation today',
			'you make nerdy charm look elite',
		],
	},
	{
		opener: 'Are you a bakery',
		payoffs: [
			'this conversation smells like sweet chaos',
			'you are serving fresh charm all day',
			'you just made this moment extra warm',
			'you are the best thing baked into this day',
			'you make every room feel more welcoming',
			'you are proof that good things rise with time',
			'you make compliments come out fresh',
			'you are dangerously delightful',
			'you are the recipe for a better mood',
			'you make life feel a little sweeter',
		],
	},
	{
		opener: 'Are you a time machine',
		payoffs: [
			'I lose track of time when we talk',
			'you just made this moment feel timeless',
			'you turned one minute into my favorite part of the day',
			'you make now feel like a highlight reel',
			'you are exactly where I want to be right now',
			'you make every second count',
			'I would happily revisit this conversation forever',
			'you make time fly in the best way',
			'you just upgraded my timeline',
			'you make the present feel like a gift',
		],
	},
	{
		opener: 'Are you a headphone jack',
		payoffs: [
			'you complete my setup perfectly',
			'you make everything sound better',
			'you are the missing piece to this mix',
			'you connect with my vibe instantly',
			'you make this conversation feel immersive',
			'you are compatibility at first sight',
			'you turn background noise into music',
			'you are plugged directly into my good mood',
			'you make static disappear',
			'you are clean audio for my chaotic day',
		],
	},
	{
		opener: 'Are you a dance floor',
		payoffs: [
			'you make everyone want to move closer',
			'you turn nervous energy into good energy',
			'you make the whole vibe come alive',
			'you are where the best moments happen',
			'you make confidence look rhythmic',
			'you bring the party without saying a word',
			'you make this chat feel like a celebration',
			'you are impossible to stand still around',
			'you make every beat feel better',
			'you are center-stage energy all night',
		],
	},
	{
		opener: 'Are you a lucky song request',
		payoffs: [
			'you showed up exactly when I needed a good one',
			'you are perfect timing in human form',
			'you just raised the quality of this whole set',
			'you make every moment feel better curated',
			'you are the request everyone secretly wanted',
			'you made this vibe instantly better',
			'you are the kind of surprise that always lands',
			'you make this session feel legendary',
			'you are a guaranteed crowd favorite',
			'you are exactly my kind of bonus track',
		],
	},
]

const pickupLines = openerPayoffGroups.flatMap(({ opener, payoffs }) =>
	payoffs.map((payoff) => `${opener}? Because ${payoff}.`),
)

module.exports = pickupLines