const sharedBirthdayCelebrities = [
	{
		name: 'Cybill Shepherd',
		yearsDifference: 24,
		relation: 'older',
		category: 'actor',
		notableThing: 'Moonlighting and Taxi Driver',
	},
	{
		name: 'Eric Idle',
		yearsDifference: 31,
		relation: 'older',
		category: 'comedian',
		notableThing: 'Monty Python and Spamalot',
	},
	{
		name: 'Vangelis',
		yearsDifference: 29,
		relation: 'older',
		category: 'musician',
		notableThing: 'the Chariots of Fire and Blade Runner scores',
	},
	{
		name: 'Perry Farrell',
		yearsDifference: 15,
		relation: 'older',
		category: 'musician',
		notableThing: 'Jane\'s Addiction and Lollapalooza',
	},
	{
		name: 'Christopher Lambert',
		yearsDifference: 17,
		relation: 'older',
		category: 'actor',
		notableThing: 'Highlander',
	},
	{
		name: 'Brendan Gleeson',
		yearsDifference: 19,
		relation: 'older',
		category: 'actor',
		notableThing: 'In Bruges and The Banshees of Inisherin',
	},
	{
		name: 'Annabella Sciorra',
		yearsDifference: 14,
		relation: 'older',
		category: 'actor',
		notableThing: 'The Sopranos and Jungle Fever',
	},
	{
		name: 'Elle Macpherson',
		yearsDifference: 10,
		relation: 'younger',
		category: 'model',
		notableThing: 'her supermodel career and Sports Illustrated covers',
	},
	{
		name: 'Lucy Lawless',
		yearsDifference: 6,
		relation: 'younger',
		category: 'actor',
		notableThing: 'Xena: Warrior Princess',
	},
	{
		name: 'Megan Hilty',
		yearsDifference: 7,
		relation: 'younger',
		category: 'actor',
		notableThing: 'Smash and Wicked',
	},
	{
		name: 'Scott Wilson',
		yearsDifference: 32,
		relation: 'older',
		category: 'actor',
		notableThing: 'The Walking Dead and In the Heat of the Night',
	},
	{
		name: 'Marina Sirtis',
		yearsDifference: 19,
		relation: 'older',
		category: 'actor',
		notableThing: 'Star Trek: The Next Generation',
	},
	{
		name: 'Ed Skrein',
		yearsDifference: 9,
		relation: 'younger',
		category: 'actor',
		notableThing: 'Deadpool and The Transporter Refueled',
	},
	{
		name: 'Ruth Nega',
		yearsDifference: 8,
		relation: 'younger',
		category: 'actor',
		notableThing: 'Loving and Preacher',
	},
	{
		name: 'PJ Morton',
		yearsDifference: 7,
		relation: 'younger',
		category: 'musician',
		notableThing: 'Maroon 5 and his solo R&B work',
	},
	{
		name: 'Kurt Thomas',
		yearsDifference: 20,
		relation: 'older',
		category: 'athlete',
		notableThing: 'his world titles in gymnastics',
	},
	{
		name: 'Jennifer Capriati',
		yearsDifference: 2,
		relation: 'younger',
		category: 'athlete',
		notableThing: 'her Grand Slam tennis titles',
	},
	{
		name: 'Joey Barton',
		yearsDifference: 8,
		relation: 'younger',
		category: 'athlete',
		notableThing: 'his Premier League football career',
	},
	{
		name: 'Nuno Gomes',
		yearsDifference: 2,
		relation: 'younger',
		category: 'athlete',
		notableThing: 'his career with Benfica and Portugal',
	},
	{
		name: 'Sam Walton',
		yearsDifference: 56,
		relation: 'older',
		category: 'business figure',
		notableThing: 'founding Walmart',
	},
	{
		name: 'John Tyler',
		yearsDifference: 184,
		relation: 'older',
		category: 'historical figure',
		notableThing: 'being the 10th president of the United States',
	},
	{
		name: 'Utada Hikaru',
		yearsDifference: 9,
		relation: 'younger',
		category: 'musician',
		notableThing: 'First Love and the Kingdom Hearts theme songs',
	},
	{
		name: 'Jason Smith',
		yearsDifference: 10,
		relation: 'younger',
		category: 'chef',
		notableThing: 'Food Network and 18th & Vine BBQ',
	},
	{
		name: 'Patrick Troughton',
		yearsDifference: 54,
		relation: 'older',
		category: 'actor',
		notableThing: 'playing the Second Doctor in Doctor Who',
	},
	{
		name: 'William M. Calder III',
		yearsDifference: 29,
		relation: 'older',
		category: 'writer',
		notableThing: 'his scholarship on classical literature and history',
	},
]

module.exports = sharedBirthdayCelebrities